### ISSUE TITLE
Could not sync

### ISSUE THREAD

**Issue by zigazajc007** [Huskehhh/MySQL#16]
Could not find artifact pro.husk:mysql:pom:1.2 in papermc-repo (https://papermc.io/repo/repository/maven-public/)

**Comment by Huskehhh** [comment]
Have you got my repo listed in your pom?

**Comment by zigazajc007** [comment]
I have this.    
<repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://papermc.io/repo/repository/maven-public/</url>
        </repository>
        <repository>
            <id>husk</id>
            <url>http://maven.husk.pro/repository/internal/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.14.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.18</version>
        </dependency>
        <dependency>
            <groupId>pro.husk</groupId>
            <artifactId>mysql</artifactId>
            <version>1.2</version>
        </dependency>
    </dependencies>

**Comment by Huskehhh** [comment]
Awesome, thanks. I've had a look, and the issue should now be fixed :)

Can you please try compile again?

**Comment by zigazajc007** [comment]
It's still the same. It look like that your dependency looks for repository only in https://papermc.io/repo/repository/maven-public/ and not in  http://maven.husk.pro/repository/internal/

**Comment by Huskehhh** [comment]
Issue was resolved.

If anyone reads this with the same issue, try using the -U flag in your build or clear your .m2 cache

Thanks
